name: Auto update

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * 1'
  workflow_dispatch:
  
jobs:
  tieba_sign:
    name: tieba_sign
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Clone repo from xxmdhs/tiebasign
      uses: actions/checkout@v2
      with:
          repository: xxmdhs/tiebasign

    - name: Start sign
      run: go run main.go

    - name: Git
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "auto update"
          git push
