name: Auto update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
jobs:
  tieba_sign:
    name: Auto update
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Clone repo 
      uses: actions/checkout@v2

    - name: Start auto update
      run: go run main.go

    - name: Git
      run: |
          git config user.name actions-user
          git config user.email action@github.com
          git add .
          git commit -m "auto update"
          git push
